version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:11.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dogs"
    ports:
      - "5432:5432"
    volumes:
      - "./sql/psql_dump.sql:/docker-entrypoint-initdb.d/1-init.sql"